# Generated by Django 3.2 on 2022-05-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPSR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
