# Generated by Django 3.2 on 2022-05-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPSR', '0003_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='gender',
        ),
    ]
