# Generated by Django 3.2 on 2022-05-30 13:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('IPSR', '0004_remove_applicant_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicant',
            new_name='Personal_info',
        ),
    ]
