# Generated by Django 3.2 on 2022-05-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPSR', '0010_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
