# Generated by Django 3.2 on 2022-06-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPSR', '0015_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
