# Generated by Django 3.2 on 2022-06-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPSR', '0016_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
